language: python
python:
  - "3.5"
before_install:
  - nvm install 6
  - npm install
install:
  - pip install -r requirements.txt
before_script:
  - python manage.py migrate
script:
  - python manage.py test
  - npm run build

notifications:
  email: false